stages:
  - test
  - build
  - deploy

tests_job:
  stage: test
  image: python:3.10
#  services:
#    - postgres:alpine
#  variables:
##    SECRET_KEY: custom_secret_key_test
#    DATABASE_ENGINE: django.db.backends.sqlite3
##    DATABASE_NAME: oc-lettings-site.sqlite3
#    DEBUG: "true"
  before_script:
  #    - apt-get update -qy
  #    - apt-get install -y python3-pip python-dev-is-python3 python3-venv
  #    - python3 -m venv env
  #    - . env/bin/activate
    - pip install -r requirements.txt
  script:
    - python3 manage.py test
    - flake8 --config setup.cfg
