test:
  services:
    - postgres:alpine
  variables:
    SECRET_KEY: custom_secret_key_test
    DATABASE_ENGINE: django.db.backends.sqlite3
    DATABASE_NAME: oc-lettings-site.sqlite3
  script:
    - apt-get update -qy
    - apt-get install -y python3-pip python-dev-is-python3 python3-venv
    - python3 -m venv env
    - env/bin/pip install -r requirements.txt
    - env/bin/python3 manage.py test
