stages:
  - test
  - build
  - deploy

#tests_job:
#  stage: test
#  image: python:3.10.6
#  before_script:
#    - pip install -r requirements.txt
#  script:
#    - python3 manage.py test
#    - flake8 --config setup.cfg

img_docker_job:
  stage: build
  image: python:3.10.6
  script:
    - docker build -t img_yml:v0.01 .
#    - docker tag img_yml:v0.01 goclusername/img_yml:v0.01
#    - docker push goclusername/img_yml:v0.01
