stages:
  - test
  - build
  - deploy

tests_job:
  stage: test
  image: python:3.10
  before_script:
    - pip install -r requirements.txt
  script:
    - python3 manage.py test
    - flake8 --config setup.cfg
