stages:
  - test
  - build
  - deploy

#tests_job:
#  stage: test
#  image: python:3.10.6
#  before_script:
#    - pip install -r requirements.txt
#  script:
#    - python3 manage.py test
#    - flake8 --config setup.cfg

img_docker_job:
  stage: build
  image: docker:24.0.4
  services:
    - docker:24.0.4-dind
  script:
    - docker build -t $HUB_DOCKER_USERNAME/$IMAGE_NAME:latest .
    - docker tag $HUB_DOCKER_USERNAME/$IMAGE_NAME:latest $HUB_DOCKER_USERNAME/$IMAGE_NAME:latest
    - echo tesssssssssssssssssttt
    - $HUB_DOCKER_PASSWORD | docker login -u $HUB_DOCKER_USERNAME --password-stdin
    - docker push $HUB_DOCKER_USERNAME/$IMAGE_NAME:latest
#    - docker tag img_yml:v0.01 goclusername/img_yml:v0.01
#    - docker push goclusername/img_yml:v0.01
