stages:
  - test
  - build

cache:
  key: "$CI_JOB_STAGE"
  paths:
    - .m2/repository

#build_job:
#  stage: build
#  services:
#    - postgres:alpine
#  variables:
#    SECRET_KEY: custom_secret_key_test
#    DATABASE_ENGINE: django.db.backends.sqlite3
#    DATABASE_NAME: oc-lettings-site.sqlite3
#    DEBUG: "true"
#  script:
#    - apt-get update -qy
#    - apt-get install -y python3-pip python-dev-is-python3 python3-venv
#    - python -m venv env
#    - . env/bin/activate
#    - pip install -r requirements.txt

pytest_job:
  stage: test
  services:
    - postgres:alpine
  variables:
    SECRET_KEY: custom_secret_key_test
    DATABASE_ENGINE: django.db.backends.sqlite3
    DATABASE_NAME: oc-lettings-site.sqlite3
    DEBUG: "true"
  script:
    - apt-get update -qy
    - apt-get install -y python3-pip python-dev-is-python3 python3-venv
    - python3 -m venv env
    - . env/bin/activate
    - pip install -r requirements.txt
    - python3 manage.py test

pytest_2_job:
  stage: build
  services:
    - postgres:alpine
  variables:
    SECRET_KEY: custom_secret_key_test
    DATABASE_ENGINE: django.db.backends.sqlite3
    DATABASE_NAME: oc-lettings-site.sqlite3
    DEBUG: "true"
  script:
#    - apt-get update -qy
#    - apt-get install -y python3-pip python-dev-is-python3 python3-venv
#    - python3 -m venv env
#    - . env/bin/activate
#    - pip install -r requirements.txt
    - python3 manage.py test