stages:
  - test
  - build
  - deploy

#tests_job:
#  stage: test
#  image: python:3.10.6
#  before_script:
#    - pip install -r requirements.txt
#  script:
#    - python3 manage.py test
#    - flake8 --config setup.cfg

#
#job:
#  image: python
#  before_script:
#    - export VERSION_IMAGE=${CI_COMMIT_TIMESTAMP}
#  script:
#    - echo ${VERSION_IMAGE}



img_docker_job:
  stage: build
  image: docker:24.0.4
  services:
    - docker:24.0.4-dind
  before_script:
    - export VERSION_IMAGE="${CI_COMMIT_TIMESTAMP}"
  script:
    - docker build -t
      ${HUB_DOCKER_USERNAME}/${IMAGE_NAME}:${VERSION_IMAGE} .
    - docker tag ${HUB_DOCKER_USERNAME}/${IMAGE_NAME}:${VERSION_IMAGE}
      ${HUB_DOCKER_USERNAME}/${IMAGE_NAME}:latest
    - echo ${HUB_DOCKER_TOKEN} |
      docker login -u ${HUB_DOCKER_USERNAME} --password-stdin
    - docker push ${HUB_DOCKER_USERNAME}/${IMAGE_NAME}:${VERSION_IMAGE}
    - docker push ${HUB_DOCKER_USERNAME}/${IMAGE_NAME}:latest
    - docker logout
